//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayoutedReader.Tests.Layouts.Examples {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleLayouts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleLayouts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LayoutedReader.Tests.Layouts.Examples.SampleLayouts", typeof(SampleLayouts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;index&gt;
        ///  &lt;file name=&quot;test_a.txt&quot; layout=&quot;layouts\test_a.xml&quot;/&gt;
        ///  &lt;file name=&quot;test_b.txt&quot; layout=&quot;layouts\test_b.xml&quot;/&gt;
        ///&lt;/index&gt;
        ///  .
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;index&gt;
        ///  &lt;file name=&quot;test_a.txt&quot; layout=&quot;layouts\test_a_layout.xml&quot; deploy=&quot;deploys\test_a_deploy.xml&quot;/&gt;
        ///  &lt;file name=&quot;test_b.txt&quot; layout=&quot;layouts\test_b_layout.xml&quot; deploy=&quot;deploys\test_b_deploy.xml&quot;/&gt;
        ///&lt;/index&gt;
        ///  .
        /// </summary>
        internal static string index_deploy {
            get {
                return ResourceManager.GetString("index_deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;deploy&gt;
        ///  &lt;filter expr=&quot;c.prop in (1,2,3)&quot;&gt;
        ///    &lt;special expr=&quot;c.atv == &apos;ASD&apos;&quot;&gt;
        ///      &lt;make tipo=&quot;R&quot; parte=&quot;C&quot;/&gt;
        ///    &lt;/special&gt;   
        ///
        ///    &lt;filter expr=&quot;c.op == &apos;A&apos;&quot;&gt;
        ///      &lt;make tipo=&quot;R&quot; parte=&quot;C&quot;/&gt;
        ///      &lt;make tipo=&quot;T&quot; parte=&quot;V&quot;/&gt;
        ///      &lt;make tipo=&quot;T&quot; parte=&quot;C&quot;/&gt;
        ///    &lt;/filter&gt;
        ///
        ///    &lt;filter expr=&quot;c.dc == &apos;Q&apos; and c.op==&apos;B&apos;&quot;&gt;
        ///      &lt;make tipo=&quot;R&quot; parte=&quot;C&quot;/&gt;
        ///      &lt;make tipo=&quot;T&quot; parte=&quot;V&quot;/&gt;
        ///      &lt;make tipo=&quot;T&quot; parte=&quot;C&quot;/&gt;
        ///    &lt;/filter&gt;
        ///
        ///    &lt;filter ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleFilters {
            get {
                return ResourceManager.GetString("SampleFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02010120303
        ///12010120174870008CCB  05L00000142   000000000000001000170018693251014000000000000000000000187655873467410000000000187655873
        ///12010120174870008CCB  05L00000148   000000000000001000117799297334346000000000000000000000129061883063906000000000129061883
        ///12010120121008005CCB  05C00015274   000000000000001000074117651300351000000000000000000000074609845499106000000000074609845
        ///12010120179610005CCB  05C00015275   000000000000001000059493371684288000000000000000000000059888450210032000000000059888450        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_a {
            get {
                return ResourceManager.GetString("test_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;deploy&gt;
        ///  &lt;filter expr=&quot;c.mvcoobrigacao == &apos;SEM COOBRIGACAO&apos;&quot;&gt;
        ///    &lt;make tipo=&quot;S&quot; parte=&quot;C&quot;/&gt;
        ///  &lt;/filter&gt;
        ///
        ///  &lt;filter expr=&quot;c.mvcoobrigacao == &apos;INTEGRAL&apos;&quot;&gt;
        ///    &lt;make tipo=&quot;I&quot; parte=&quot;C&quot;/&gt;
        ///    &lt;make tipo=&quot;I&quot; parte=&quot;V&quot;/&gt;
        ///  &lt;/filter&gt;
        ///
        ///  &lt;special expr=&quot;c.MVLANC_COMPRADOR == &apos;COSTA&apos;&quot;&gt;
        ///    &lt;make tipo=&quot;Y&quot; parte=&quot;C&quot;/&gt;
        ///  &lt;/special&gt;
        ///&lt;/deploy&gt;.
        /// </summary>
        internal static string test_a_deploy {
            get {
                return ResourceManager.GetString("test_a_deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;layout&gt;
        ///  &lt;header name=&quot;ACUMMOV-DATULTMOV&quot; type=&quot;date(yyyyMMdd)&quot; /&gt;
        ///
        ///  &lt;field name=&quot;MVTIPO-IF&quot; type=&quot;string(5)&quot; /&gt;
        ///  &lt;field name=&quot;MVCOMPRADOR-CODIGO&quot; type=&quot;number(8)&quot; /&gt;
        ///  &lt;field name=&quot;MVVENDEDOR-CODIGO&quot; type=&quot;number(8)&quot; /&gt;
        ///  &lt;field name=&quot;MVIF-CODIGO&quot; type=&quot;string(14)&quot; /&gt;
        ///  &lt;field name=&quot;MVDATA-EMISSAO&quot; type=&quot;date(yyyyMMdd)&quot; /&gt;
        ///  &lt;field name=&quot;MVDATA-VENCIMENTO&quot; type=&quot;date(yyyyMMdd)&quot; /&gt;
        ///  &lt;field name=&quot;MVCOOBRIGACAO&quot; type=&quot;string(15)&quot; /&gt;
        ///  &lt;field name=&quot;MVOPER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_a_layout {
            get {
                return ResourceManager.GetString("test_a_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20101203
        ///CCB  184650081846500810I00008111   2010092720121024INTEGRAL       201012010001043201012011926363700000000000000000000002000000000000000000000000100000000000000000201012010000000000000000COSTA 20101201182511      201012011825110000000000000000
        ///CCB  704304047643000609B00014903   2009021720111201SEM COOBRIGACAO201012010060040201011301925997000000000000000000000000000000000000000000000000100000000000000000201012010000000000000000      20101201093011      201012010930110000000000000000
        ///CCB  704304047 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_b {
            get {
                return ResourceManager.GetString("test_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;deploy&gt;
        ///  
        ///&lt;/deploy&gt;.
        /// </summary>
        internal static string test_b_deploy {
            get {
                return ResourceManager.GetString("test_b_deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;layout&gt;
        ///  &lt;header name=&quot;DCTIPO-REG-H&quot; type=&quot;string(1)&quot; /&gt;
        ///  &lt;header name=&quot;DCDATULTMOV&quot; type=&quot;date(yyyyMMdd)&quot; /&gt;
        ///  &lt;header name=&quot;DCNUMDIASUTEIS&quot; type=&quot;number(2)&quot; /&gt;
        ///  &lt;header name=&quot;FILLER&quot; type=&quot;string(112)&quot; /&gt;
        ///
        ///  &lt;field name=&quot;DCTIPO-REG-D&quot; type=&quot;string(1)&quot; /&gt;
        ///  &lt;field name=&quot;DCDATOP&quot; type=&quot;date(yyyyMMdd)&quot; /&gt;
        ///  &lt;field name=&quot;DCDETENTOR&quot; type=&quot;number(8)&quot; /&gt;
        ///  &lt;field name=&quot;DCTIPOIF&quot; type=&quot;string(5)&quot; /&gt;
        ///  &lt;field name=&quot;DCIF&quot; type=&quot;string(14)&quot; /&gt;
        ///  &lt;field name=&quot;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_b_layout {
            get {
                return ResourceManager.GetString("test_b_layout", resourceCulture);
            }
        }
    }
}
